<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>top.tangtian.designpattern</groupId>
    <artifactId>design-pattern</artifactId>
    <packaging>pom</packaging>

    <name>designpattern</name>
    <modules>
        <module>chain</module>
    </modules>

    <parent>
        <groupId>top.tangtian</groupId>
        <artifactId>demo</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <start-class>top.tangtian.designpattern.chain.http.ChainDemo</start-class>
        <java.version>21</java.version>
        <log4jdbc.log4j2.version>1.16</log4jdbc.log4j2.version>
        <rest.assured.version>2.3.3</rest.assured.version>
    </properties>

    <dependencies>
    </dependencies>
    <build>

    </build>

</project>
